spring.application.name=ems-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=hsuan
spring.datasource.password=

# hibernate automatically create database tables based on jpa entity
spring.jpa.hibernate.ddl-auto=update