# Optional profile for local Vault testing (Vault must be running on localhost:8200)
spring.cloud.vault.enabled=true
spring.config.import=optional:vault://

spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=ems-vault-token
spring.cloud.vault.authentication=TOKEN

spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=ems-backend
