spring.application.name=sms-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/sms
spring.datasource.username=hsuan
spring.datasource.password=

# hibernate automatically create database tables based on jpa entity
spring.jpa.hibernate.ddl-auto=update


server.port=8081