# jenkins service
# start docker container in local env
services:
  jenkins:
    build: .
    image: jenkins-with-docker
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8081:8080"                      # Jenkins UI -> http://localhost:8081
      - "50000:50000"                    # Jenkins  agent port
    volumes:
      - jenkins_home:/var/jenkins_home   # persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock
      - ${COMPOSE_DIR:-..}:/home/ec2-user/ems-backend  # jenkins service point to ems-backend, so local project can access to this pipeline
      - ${SSH_KEY_PATH:-/Users/hsuan/.ssh/ems-jenkins-key.pem}:/run/secrets/ec2-ssh-key.pem:ro
    env_file:
      - .env
    environment:
      EC2_HOST: ${EC2_HOST:-18.225.218.150}

volumes:
  jenkins_home:
